java -jar ./jars/temp-controller.jar &
java -jar ./jars/humidity-controller.jar &
java -jar ./jars/intrusion-controller.jar &
java -jar ./jars/fire-alarm-controller.jar &
java -jar ./jars/sprinkler-controller.jar &
java -jar ./jars/temp-sensor.jar &
java -jar ./jars/humidity-sensor.jar &
java -jar ./jars/intrusion-sensor.jar &
java -jar ./jars/fire-sensor.jar &